apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: df-reporter
spec:
  selector:
    matchLabels:
      app: df-reporter
  template:
    metadata:
      labels:
        app: df-reporter
    spec:
      containers:
      - name: df-reporter
        image: gcr.io/PROJECT-ID/df-reporter
      - name: prom-to-sd
        image: gcr.io/google-containers/prometheus-to-sd:v0.9.2
        # About this image
        # https://github.com/GoogleCloudPlatform/k8s-stackdriver/tree/master/prometheus-to-sd
        command:
        - /monitor
        - --stackdriver-prefix=custom.googleapis.com
        - --source=df-reporter:http://localhost:8080/metrics?whitelisted=disk_all,disk_used,disk_free&customResourceType=k8s_node&customLabels[project_id]&customLabels[location]=asia-east1-a&customLabels[cluster_name]&customLabels[node_name]=$(NODE_NAME)
        # About k8s_node
        # https://cloud.google.com/monitoring/api/resources#tag_k8s_node
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
